version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - slack/notify
workflows:
  example-workflow:
    jobs:
      - example-job